import { ExpedienteStatus } from "./types";

export const ESTADOS: ExpedienteStatus[] = [
  "pasa p/archivos",
  "pasa p/archivos con acuerdo",
  "pasa p/archivos solucionado",
  "pasa p/archivos por acuerdo",
  "pasa p/ archivo-armario p/ limbo",
  "pasa p/jurídico p/imputar",
  "para imputar",
  "p/asesoría legal dpto jurídico p/evaluación",
  "pase dpto jurídico p/medida preventiva",
  "p/dpto jurídico p/ análisis",
  "sale cedula para la consumidora",
  "sale cedula p/ la denunciada",
  "la consumidora se notificó en este org.",
  "reprogramación de audiencia",
  "incomparecencia de las partes",
  "expediente no armado, esperando documental",
  "p/reprogramar",
  "p/ homologación de la direc.",
  "archivo a despacho p/ copias certificadas",
  "plazo de 5 días",
  "plazo de 10 días",
  "plazo de 20 días",
  "plazo de 30 días",
  "plazo de 90 días",
  "a la espera que responda el consumidor",
  "las partes informaran el cumplimiento",
  "a espera que responda la empresa",
  "la consumidora tiene que informar el cumplimiento",
  "el consumidor va a venir a firmar la acta",
  "planteo de recurso jerárquico",
  "entró escrito del consumidor",
  "a despacho para copia certificada / p/ imputar",
  "pasa p/ archivo se le resolvió",
  "pasa p/caja",
  "plazo p/ la denunciada p/ cumplir con la propuesta- en caja",
  "plazo p/ consumidora p/ informar el cumplimiento- en caja",
  "pase a jurídico",
];

export const HORARIOS_AUDIENCIA = ["08:00", "09:00", "10:00", "11:00", "12:00"] as const;
